// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iplkrtiufldtwzkefewh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwbGtydGl1ZmxkdHd6a2VmZXdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MTU1MjgsImV4cCI6MjA2MzA5MTUyOH0.TVyjxbt-NU3kfpGTxmYk-ivfvRmLleL7VjLEHwp09JM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);